module: "src.agents.FastChatAgent"
parameters:
    name: "FastChat-guanaco-33b-merged"
    # worker_address: "http://166.111.5.162:49991" # Do not use worker_address directly
    controller_address: "http://166.111.5.162:49999"
    model_name: "guanaco-33b-merged"
    max_new_tokens: 50
    temperature: 0
    top_p: 0