module: "src.agents.FastChatAgent"
parameters:
    name: "FastChat-guanaco-65b"
    controller_address: "http://localhost:49999"
    model_name: "guanaco-65b-merged"
    max_new_tokens: 512
    temperature: 0.7
