module: "src.agents.FastChatAgent"
parameters:
    name: "FastChat-vicuna-7b"
    controller_address: "http://localhost:49999"
    model_name: "openchat_8192"
    max_new_tokens: 512
    temperature: 0.7
