module: "src.agents.FastChatAgent"
parameters:
    name: "FastChat-vicuna-7b"
    controller_address: "http://localhost:21001"
    model_name: "vicuna-7b-full"
    max_new_tokens: 512
    temperature: 0.7
