module: "src.agents.FastChatAgent"
parameters:
    name: "FastChat-vicuna-7b"
    # worker_address: "http://166.111.5.162:49991" # Do not use worker_address directly
    controller_address: "http://166.111.5.162:49999"
    model_name: "vicuna-7b-full"
    max_new_tokens: 512
    temperature: 0
    top_p: 0
