module: "src.agents.FastChatAgent"
parameters:
    name: "FastChat-vicuna-13b"
    controller_address: "http://localhost:49999"
    model_name: "vicuna-13b-full"
    max_new_tokens: 512
    temperature: 0.7
