module: "src.agents.FastChatAgent"
parameters:
    name: "FastChat-vicuna-33b-v1.3"
    controller_address: "http://localhost:49999"
    model_name: "vicuna-33b-v1.3"
    max_new_tokens: 512
    temperature: 0.7
