module: "src.agents.FastChatAgent"
parameters:
    name: "FastChat-WizardLM-30B-V1.0"
    # worker_address: "http://166.111.5.162:49991" # Do not use worker_address directly
    controller_address: "http://192.18.158.210:9999"
    worker_limit: 5
    model_name: "WizardLM-30B-V1.0-merged"
    max_new_tokens: 512
    temperature: 0.7
