module: "src.agents.FastChatAgent"
parameters:
    name: "FastChat-WizardLM-13B-V1.0"
    controller_address: "http://localhost:49999"
    model_name: "WizardLM-13B-V1.0-merged"
    max_new_tokens: 40
    temperature: 0.7
