module: src.tasks.single_round_tasks.SingleRoundTask
parameters:
  acc_type: EM
  extract_answer: true
  file-pattern:
    grade-1-Math-FIB: '**/grade-1-Math-FIB.jsonl'
    grade-10-Biology-FIB: '**/grade-10-Biology-FIB.jsonl'
    grade-10-Chemistry-FIB: '**/grade-10-Chemistry-FIB.jsonl'
    grade-10-Chinese-FIB: '**/grade-10-Chinese-FIB.jsonl'
    grade-10-English-FIB: '**/grade-10-English-FIB.jsonl'
    grade-10-Geography-FIB: '**/grade-10-Geography-FIB.jsonl'
    grade-10-History-FIB: '**/grade-10-History-FIB.jsonl'
    grade-10-Math-FIB: '**/grade-10-Math-FIB.jsonl'
    grade-10-Physics-FIB: '**/grade-10-Physics-FIB.jsonl'
    grade-10-Politics-FIB: '**/grade-10-Politics-FIB.jsonl'
    grade-11-Biology-FIB: '**/grade-11-Biology-FIB.jsonl'
    grade-11-Chemistry-FIB: '**/grade-11-Chemistry-FIB.jsonl'
    grade-11-Chinese-FIB: '**/grade-11-Chinese-FIB.jsonl'
    grade-11-English-FIB: '**/grade-11-English-FIB.jsonl'
    grade-11-Geography-FIB: '**/grade-11-Geography-FIB.jsonl'
    grade-11-History-FIB: '**/grade-11-History-FIB.jsonl'
    grade-11-Math-FIB: '**/grade-11-Math-FIB.jsonl'
    grade-11-Physics-FIB: '**/grade-11-Physics-FIB.jsonl'
    grade-11-Politics-FIB: '**/grade-11-Politics-FIB.jsonl'
    grade-12-Biology-FIB: '**/grade-12-Biology-FIB.jsonl'
    grade-12-Chemistry-FIB: '**/grade-12-Chemistry-FIB.jsonl'
    grade-12-Chinese-FIB: '**/grade-12-Chinese-FIB.jsonl'
    grade-12-English-FIB: '**/grade-12-English-FIB.jsonl'
    grade-12-Geography-FIB: '**/grade-12-Geography-FIB.jsonl'
    grade-12-History-FIB: '**/grade-12-History-FIB.jsonl'
    grade-12-Math-FIB: '**/grade-12-Math-FIB.jsonl'
    grade-12-Physics-FIB: '**/grade-12-Physics-FIB.jsonl'
    grade-12-Politics-FIB: '**/grade-12-Politics-FIB.jsonl'
    grade-2-Math-FIB: '**/grade-2-Math-FIB.jsonl'
    grade-3-Math-FIB: '**/grade-3-Math-FIB.jsonl'
    grade-4-Chinese-FIB: '**/grade-4-Chinese-FIB.jsonl'
    grade-4-English-FIB: '**/grade-4-English-FIB.jsonl'
    grade-4-Math-FIB: '**/grade-4-Math-FIB.jsonl'
    grade-5-Chinese-FIB: '**/grade-5-Chinese-FIB.jsonl'
    grade-5-English-FIB: '**/grade-5-English-FIB.jsonl'
    grade-5-Math-FIB: '**/grade-5-Math-FIB.jsonl'
    grade-6-Chinese-FIB: '**/grade-6-Chinese-FIB.jsonl'
    grade-6-English-FIB: '**/grade-6-English-FIB.jsonl'
    grade-6-Math-FIB: '**/grade-6-Math-FIB.jsonl'
    grade-7-Chinese-FIB: '**/grade-7-Chinese-FIB.jsonl'
    grade-7-English-FIB: '**/grade-7-English-FIB.jsonl'
    grade-7-Math-FIB: '**/grade-7-Math-FIB.jsonl'
    grade-8-Biology-FIB: '**/grade-8-Biology-FIB.jsonl'
    grade-8-Chinese-FIB: '**/grade-8-Chinese-FIB.jsonl'
    grade-8-English-FIB: '**/grade-8-English-FIB.jsonl'
    grade-8-Geography-FIB: '**/grade-8-Geography-FIB.jsonl'
    grade-8-History-FIB: '**/grade-8-History-FIB.jsonl'
    grade-8-Math-FIB: '**/grade-8-Math-FIB.jsonl'
    grade-8-Physics-FIB: '**/grade-8-Physics-FIB.jsonl'
    grade-8-Politics-FIB: '**/grade-8-Politics-FIB.jsonl'
    grade-9-Biology-FIB: '**/grade-9-Biology-FIB.jsonl'
    grade-9-Chemistry-FIB: '**/grade-9-Chemistry-FIB.jsonl'
    grade-9-Chinese-FIB: '**/grade-9-Chinese-FIB.jsonl'
    grade-9-English-FIB: '**/grade-9-English-FIB.jsonl'
    grade-9-Geography-FIB: '**/grade-9-Geography-FIB.jsonl'
    grade-9-History-FIB: '**/grade-9-History-FIB.jsonl'
    grade-9-Math-FIB: '**/grade-9-Math-FIB.jsonl'
    grade-9-Physics-FIB: '**/grade-9-Physics-FIB.jsonl'
    grade-9-Politics-FIB: '**/grade-9-Politics-FIB.jsonl'
  language: cn
  name: FIB-cn-qa
  path: data/step-0914/step2/step2_cn/data/FIB
