module: src.tasks.single_round_tasks.SingleRoundTask
parameters:
  acc_type: EM
  file-pattern:
    traditional/summary: '**/cn/*'
  language: cn
  name: step1_cn_sum
  path: data/summary
  workers: 10
  extract_answer: False
