module: src.tasks.single_round_tasks.SingleRoundTask
parameters:
  acc_type: EM
  file-pattern:
    inference/logic/drop: '**/inference/logic/drop.jsonl'
    knowledge/factual-qa/narrativeqa: '**/knowledge/factual-qa/narrativeqa.jsonl'
    knowledge/factual-qa/no_background_squad_data: '**/knowledge/factual-qa/no_background_squad_data.jsonl'
    knowledge/science-qa/no_background_cmrc_data: '**/knowledge/science-qa/no_background_cmrc_data.jsonl'
    knowledge/science-qa/no_background_webqa_data: '**/knowledge/science-qa/no_background_webqa_data.jsonl'
    traditional/machine-translation/translate-en-zh: '**/traditional/machine-translation/translate-en-zh.jsonl'
    traditional/machine-translation/translate-zh-en: '**/traditional/machine-translation/translate-zh-en.jsonl'
    traditional/reading-comprehension/cail_data: '**/traditional/reading-comprehension/cail_data.jsonl'
    traditional/reading-comprehension/drcd_data: '**/traditional/reading-comprehension/drcd_data.jsonl'
    traditional/reading-comprehension/medicine_data: '**/traditional/reading-comprehension/medicine_data.jsonl'
    traditional/reading-comprehension/military_data: '**/traditional/reading-comprehension/military_data.jsonl'
    traditional/reading-comprehension/webqa_data: '**/traditional/reading-comprehension/webqa_data.jsonl'
    traditional/summary/cnn_dailymail3.0.0: '**/traditional/summary/cnn_dailymail3.0.0.jsonl'
    traditional/summary/samsum: '**/traditional/summary/samsum.jsonl'
    traditional/summary/xsum: '**/traditional/summary/xsum.jsonl'
  language: cn
  name: step1_cn_qa
  path: data/STEP-I/step1_cn/data
  shot: 0
  workers: 10
