module: src.tasks.single_round_tasks.SingleRoundTask
parameters:
  acc_type: MUL
  file-pattern:
    inference/legal/lsat-ar: '**/inference/legal/lsat-ar.jsonl'
    inference/legal/lsat-lr: '**/inference/legal/lsat-lr.jsonl'
    inference/legal/lsat-rc: '**/inference/legal/lsat-rc.jsonl'
    inference/logic/NumGLUE-Type3: '**/inference/logic/NumGLUE-Type3.jsonl'
    inference/logic/anli: '**/inference/logic/anli.jsonl'
    inference/logic/boolean_expressions: '**/inference/logic/boolean_expressions.jsonl'
    inference/logic/formal_fallacies: '**/inference/logic/formal_fallacies.jsonl'
    inference/logic/geometric_shapes: '**/inference/logic/geometric_shapes.jsonl'
    inference/logic/logical_deduction_five_objects: '**/inference/logic/logical_deduction_five_objects.jsonl'
    inference/logic/logical_deduction_seven_objects: '**/inference/logic/logical_deduction_seven_objects.jsonl'
    inference/logic/logical_deduction_three_objects: '**/inference/logic/logical_deduction_three_objects.jsonl'
    inference/logic/logiqa-en: '**/inference/logic/logiqa-en.jsonl'
    inference/logic/multi_nli: '**/inference/logic/multi_nli.jsonl'
    inference/logic/navigate: '**/inference/logic/navigate.jsonl'
    inference/logic/penguins_in_a_table: '**/inference/logic/penguins_in_a_table.jsonl'
    inference/logic/reclor: '**/inference/logic/reclor.jsonl'
    inference/logic/temporal_sequences: '**/inference/logic/temporal_sequences.jsonl'
    inference/logic/time_dial: '**/inference/logic/time_dial.jsonl'
    inference/logic/tracking_shuffled_objects_five_objects: '**/inference/logic/tracking_shuffled_objects_five_objects.jsonl'
    inference/logic/tracking_shuffled_objects_seven_objects: '**/inference/logic/tracking_shuffled_objects_seven_objects.jsonl'
    inference/logic/tracking_shuffled_objects_three_objects: '**/inference/logic/tracking_shuffled_objects_three_objects.jsonl'
    inference/logic/web_of_lies: '**/inference/logic/web_of_lies.jsonl'
    knowledge/commonsense-qa/causal_judgement: '**/knowledge/commonsense-qa/causal_judgement.jsonl'
    knowledge/commonsense-qa/date_understanding: '**/knowledge/commonsense-qa/date_understanding.jsonl'
    knowledge/commonsense-qa/movie_recommendation: '**/knowledge/commonsense-qa/movie_recommendation.jsonl'
    knowledge/commonsense-qa/ruin_names: '**/knowledge/commonsense-qa/ruin_names.jsonl'
    knowledge/commonsense-qa/sports_understanding: '**/knowledge/commonsense-qa/sports_understanding.jsonl'
    knowledge/commonsense-qa/swagregular: '**/knowledge/commonsense-qa/swagregular.jsonl'
    knowledge/science-qa/ai2_arcARC-Challenge: '**/knowledge/science-qa/ai2_arcARC-Challenge.jsonl'
    knowledge/science-qa/ai2_arcARC-Easy: '**/knowledge/science-qa/ai2_arcARC-Easy.jsonl'
    knowledge/science-qa/openbookqa: '**/knowledge/science-qa/openbookqa.jsonl'
    knowledge/science-qa/piqa: '**/knowledge/science-qa/piqa.jsonl'
    knowledge/science-qa/pubmed_qapqa_artificial: '**/knowledge/science-qa/pubmed_qapqa_artificial.jsonl'
    knowledge/science-qa/pubmed_qapqa_labeled: '**/knowledge/science-qa/pubmed_qapqa_labeled.jsonl'
    knowledge/science-qa/qasc: '**/knowledge/science-qa/qasc.jsonl'
    knowledge/science-qa/sciq: '**/knowledge/science-qa/sciq.jsonl'
    math/aqua_ratraw: '**/math/aqua_ratraw.jsonl'
    math/math_qa: '**/math/math_qa.jsonl'
    math/sat-math: '**/math/sat-math.jsonl'
    traditional/reading-comprehension/raceall: '**/traditional/reading-comprehension/raceall.jsonl'
    traditional/reading-comprehension/racehigh: '**/traditional/reading-comprehension/racehigh.jsonl'
    traditional/reading-comprehension/racemiddle: '**/traditional/reading-comprehension/racemiddle.jsonl'
    traditional/reading-comprehension/super_gluemultirc: '**/traditional/reading-comprehension/super_gluemultirc.jsonl'
    traditional/sentimental-analysis/emo: '**/traditional/sentimental-analysis/emo.jsonl'
    traditional/sentimental-analysis/imdb: '**/traditional/sentimental-analysis/imdb.jsonl'
  language: en
  name: step1_en_mul
  path: data/STEP-I/step1_en/data
  shot: 0
  workers: 10
