module: src.tasks.single_round_tasks.SingleRoundTask
parameters:
  acc_type: MUL
  file-pattern:
    inference/legal/lsat-ar: '**/inference/legal/lsat-ar.jsonl'
    inference/legal/lsat-lr: '**/inference/legal/lsat-lr.jsonl'
    inference/legal/lsat-rc: '**/inference/legal/lsat-rc.jsonl'
    inference/logic/Com2Sense_all: '**/inference/logic/Com2Sense_all.jsonl'
    inference/logic/NumGLUE-Type3: '**/inference/logic/NumGLUE-Type3.jsonl'
    inference/logic/anli: '**/inference/logic/anli.jsonl'
    inference/logic/commonsense_qa: '**/inference/logic/commonsense_qa.jsonl'
    inference/logic/cosmos_qa: '**/inference/logic/cosmos_qa.jsonl'
    inference/logic/logiqa-zh: '**/inference/logic/logiqa-zh.jsonl'
    inference/logic/multi_nli: '**/inference/logic/multi_nli.jsonl'
    inference/logic/reclor: '**/inference/logic/reclor.jsonl'
    inference/logic/snli: '**/inference/logic/snli.jsonl'
    inference/logic/super_gluecopa: '**/inference/logic/super_gluecopa.jsonl'
    inference/logic/time_dial: '**/inference/logic/time_dial.jsonl'
    inference/logic/xnlien: '**/inference/logic/xnlien.jsonl'
    knowledge/commonsense-qa/swagregular: '**/knowledge/commonsense-qa/swagregular.jsonl'
    knowledge/science-qa/ai2_arcARC-Challenge: '**/knowledge/science-qa/ai2_arcARC-Challenge.jsonl'
    knowledge/science-qa/ai2_arcARC-Easy: '**/knowledge/science-qa/ai2_arcARC-Easy.jsonl'
    knowledge/science-qa/openbookqa: '**/knowledge/science-qa/openbookqa.jsonl'
    knowledge/science-qa/piqa: '**/knowledge/science-qa/piqa.jsonl'
    knowledge/science-qa/pubmed_qapqa_artificial: '**/knowledge/science-qa/pubmed_qapqa_artificial.jsonl'
    knowledge/science-qa/pubmed_qapqa_labeled: '**/knowledge/science-qa/pubmed_qapqa_labeled.jsonl'
    knowledge/science-qa/qasc: '**/knowledge/science-qa/qasc.jsonl'
    knowledge/science-qa/sat-en: '**/knowledge/science-qa/sat-en.jsonl'
    knowledge/science-qa/sat-en-without-passage: '**/knowledge/science-qa/sat-en-without-passage.jsonl'
    knowledge/science-qa/sciq: '**/knowledge/science-qa/sciq.jsonl'
    math/aqua-rat: '**/math/aqua-rat.jsonl'
    math/math_qa: '**/math/math_qa.jsonl'
    math/sat-math: '**/math/sat-math.jsonl'
    traditional/reading-comprehension/raceall: '**/traditional/reading-comprehension/raceall.jsonl'
    traditional/reading-comprehension/racehigh: '**/traditional/reading-comprehension/racehigh.jsonl'
    traditional/reading-comprehension/racemiddle: '**/traditional/reading-comprehension/racemiddle.jsonl'
    traditional/reading-comprehension/super_gluemultirc: '**/traditional/reading-comprehension/super_gluemultirc.jsonl'
    traditional/sentimental-analysis/emo: '**/traditional/sentimental-analysis/emo.jsonl'
  language: cn
  name: step1_cn_mul
  path: data/STEP-I/step1_cn/data
  shot: 0
  workers: 10
