module: src.tasks.SingleRoundTask
parameters:
  file-pattern:
    traditional/summary/samsum: "**/traditional/summary/samsum.jsonl"
    traditional/summary/xsum: "**/traditional/summary/xsum.jsonl"
    traditional/summary/cnn_dailymail3.0.0: "**/traditional/summary/cnn_dailymail3.0.0.jsonl"
  language: cn
  name: step1_cn-traditional-summary
  path: data/step1_cn/data
  prompt: "{content} 总结："
