module: "src.tasks.OSInteraction"
parameters:
  name: "OS-Interaction"
  match_problem: true
  check_problem: true
  round_limit: 3

  docker_config:
    localhost: local-os
    directory: data/os_interaction/res/dockerfiles

  scripts:
    directory: data/os_interaction/res/scripts

  data_config:
    files:
      - problem_file: data/os_interaction/data/logs/*.json
        script_dir: data/os_interaction/res/scripts/

      - problem_file: data/os_interaction/data/yuhao/*.json
        script_dir: data/os_interaction/res/scripts/

      - problem_file: data/os_interaction/data/annotator/李子谋/ac.json
        script_dir: data/os_interaction/res/scripts/

      - problem_file: data/os_interaction/data/annotator/extracted/*.json
        script_dir: data/os_interaction/res/scripts/

      - problem_file: data/os_interaction/problems/yuhao/new.json
        script_dir: data/os_interaction/problems/yuhao/

      - problem_file: data/os_interaction/problems/zhc/new.json
        script_dir: data/os_interaction/problems/zhc/

      - problem_file: data/os_interaction/problems/data-bootstrapped.json
        script_dir: data/os_interaction/res/scripts/

    bk: []
    ignore: []
