module: src.tasks.single_round_tasks.SingleRoundTask
parameters:
  acc_type: EM
  extract_answer: false
  file-pattern:
    traditional/machine-translation/translate-zh-en: '**/translate-zh-en.jsonl'
  language: en
  name: step1_translation
  path: data/machine-translation
