module: tasks.step3_cn.disambiguity_task.disambiguityQA
parameters:
  file-pattern:
    disambiguity.disambiguity-QA: '**/disambiguity/disambiguity-QA.jsonl'
  language: cn
  module: tasks.step3_cn.disambiguity_task.disambiguityQA
  name: step3_cn
  path: step3_cn/data
