module: src.tasks.SingleRoundTask
parameters:
  file-pattern:
    alignment-with-human-values/chinese-ethnics: '**/alignment-with-human-values/chinese-ethnics.jsonl'
    alignment-with-human-values/crow-pairs: '**/alignment-with-human-values/crow-pairs.jsonl'
    alignment-with-human-values/ethos_binary: '**/alignment-with-human-values/ethos_binary.jsonl'
    alignment-with-human-values/stereoset: '**/alignment-with-human-values/stereoset.jsonl'
    disambiguity/disambiguity-TF: '**/disambiguity/disambiguity-TF.jsonl'
    disinformation/fake_trivia: '**/disinformation/fake_trivia.jsonl'
    disinformation/hellaswag_cn: '**/disinformation/hellaswag_cn.jsonl'
    disinformation/hq_trivia: '**/disinformation/hq_trivia.jsonl'
    disinformation/nota_trivia: '**/disinformation/nota_trivia.jsonl'
    disinformation/truthfulqa_trivia: '**/disinformation/truthfulqa_trivia.jsonl'
    misleads/hindsight-neglect: '**/misleads/hindsight-neglect.jsonl'
    misleads/into-the-unknown: '**/misleads/into-the-unknown.jsonl'
    misleads/memo-trap: '**/misleads/memo-trap.jsonl'
    misleads/modus-tollens: '**/misleads/modus-tollens.jsonl'
    misleads/neqa: '**/misleads/neqa.jsonl'
    misleads/prompt-injection_sequence-probability: '**/misleads/prompt-injection_sequence-probability.jsonl'
    misleads/redefine: '**/misleads/redefine.jsonl'
    misleads/repetitive-algebra: '**/misleads/repetitive-algebra.jsonl'
    misleads/resisting-correction: '**/misleads/resisting-correction.jsonl'
    misleads/sig-figs: '**/misleads/sig-figs.jsonl'
    self-identity/role-play: '**/self-identity/role-play.jsonl'
  language: cn
  name: step3_cn
  path: data/step3_cn/data
