module: src.tasks.single_round_tasks.SingleRoundTask
parameters:
  acc_type: MUL
  extract_answer: true
  file-pattern:
    flip_coin: '**/flip_coin.jsonl'
  language: cn
  name: real-world
  path: data/step-0904/step1_cn/data/knowledge/real-world
